package com.dynatrace.easytravel.launcher.httpd;

/**
 * A route generator is a helper which determines how the route-portion in a BalanceMember
 * section gets written.<br />
 * <br />
 * It creates a string based on a host name and a port number.
 * 
 * Example:
 * 
 * For <tt>BalancerMember ajp://localhost:8280 route=jvmRoute-8280 connectiontimeout=10 retry=120</tt>
 * 
 * the portion <tt>jvmRoute-8280</tt> is being generated by a RouteGenerator.
 * 
 * @see {@link BalancerMember}
 * 
 * @author cwat-rpilz
 *
 */
public interface RouteGenerator {

	/**
	 * Generates route portions of pattern <tt>jvmRoute-ajpPort</tt>.
	 * 
	 * @author cwat-rpilz
	 *
	 */
	public static final class DefaultRouteGen implements RouteGenerator {

		@Override
		public String genRoute(String host, int ajpPort) {
			return new StringBuilder().append("jvmRoute-").append(ajpPort).toString();
		}
		
	}	

	/**
	 * Generates the route portion of a BalancerMember section within httpd.conf
	 * 
	 * @param host the host name as parameter for generating a distinct route attribute
	 * @param ajpPort the port number as parameter for generating a distinct route attribute
	 * @return a route portion based on host and port number
	 * 
	 * @author cwat-rpilz
	 */
	String genRoute(String host, int ajpPort);
	
}
